version: 1.0.{build}

# docker support
#image: Visual Studio 2017

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


branches:
    only:
        - master

skip_tags: true

max_jobs: 100

build: none

clone_folder: c:\projects\sos
clone_depth: 50
shallow_clone: false

environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_VERSION: 3.6

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # 
    # add docker
    #- pip install docker
    # packages required by SoS
    - pip install spyder jedi notebook nbconvert nbformat pyyaml psutil tqdm 
    - pip install fasteners pygments ipython ptpython networkx pydot pydotplus nose 
    # https://github.com/jupyter/jupyter/issues/150
    - pip install entrypoints markdown
    - pip install jupyter wand numpy pandas
    # install github version of sos
    - pip install git+https://github.com/vatlab/sos.git
    - pip install pytest
    - pip install . -U
    - python -m sos_notebook.install

test_script:
    - cd test
    - git clone https://github.com/vatlab/sos.git sos_tests
    - pytest -x -v 

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
    - provider: Email
      to:
        - ben.bob@gmail.com
      on_build_status_changed: true


