version: 1.0.{build}

# docker support
#image: Visual Studio 2017

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


branches:
    only:
        - master
        - mini_test

skip_tags: true

max_jobs: 100

build: none

clone_folder: c:\projects\sos
clone_depth: 50
shallow_clone: false

environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_VERSION: 3.6

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - pip install pytest sos
    - pip install . -U
    - python -m sos_notebook.install

test_script:
    - cd test
    - python test_basic.py

notifications:
    - provider: Email
      to:
        - ben.bob@gmail.com
      on_build_status_changed: true


