version: 1.0.{build}

# docker support
#image: Visual Studio 2017

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


branches:
    only:
        - master

skip_tags: true

max_jobs: 100

build: none

clone_folder: c:\projects\sos
clone_depth: 50
shallow_clone: false

environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_VERSION: 3.6

        - PYTHON: "C:\\Miniconda35-x64"
          PYTHON_VERSION: 3.5

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # 
    # add docker
    - pip install docker
    # packages required by SoS
    - pip install spyder jedi notebook nbconvert nbformat pyyaml psutil tqdm 
    - pip install fasteners pygments ipython ptpython networkx pydot pydotplus nose 
    # https://github.com/jupyter/jupyter/issues/150
    - pip install entrypoints
    - pip install jupyter wand
    # install r kernel
    - conda install -c r r-essentials r-feather
    - conda install -c conda-forge feather-format
    # for python2 kernel
    - conda create -n ipykernel_py2 python=2 ipykernel
    - activate ipykernel_py2
    - python -m ipykernel install --user
    - deactivate
 
    # used by ./run_tests for coverage
    #- pip install coverage
    #- pip install codacy-coverage
    # install bash kernel
    #- pip install bash_kernel
    #- python -m bash_kernel.install

    # install sos
    - pip install pytest
    - python setup.py install

test_script:
    - cd test
    - pytest -x -v core
    - pytest -x -v jupyter
    - pytest -x -v bioinfo
    - pytest -x -v PBS
      #- pytest -x -v rq
      #- pytest -x -v docker
      #- pytest -x -v Bash
      #- pytest -x -v JavaScript
    - pytest -x -v Python2
    - pytest -x -v Python3
    - pytest -x -v R
      #- pytest -x -v SAS
      #- pytest -x -v Matlab
      #- pytest -x -v Octave

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# do not report coverage because codacy only accept coverage for each commit
#
#on_success:
#    - coverage xml
#    - python-codacy-coverage -r coverage.xml

notifications:
    - provider: Email
      to:
        - ben.bob@gmail.com
      on_build_status_changed: true


